-- Replace EnquiryStatus (16 -> 9 values) and LossReason (7 -> 3 values) with the client's
-- simplified pipeline model. Existing data is remapped via CASE, not dropped.

-- Move old enums out of the way
ALTER TYPE "EnquiryStatus" RENAME TO "EnquiryStatus_old";
ALTER TYPE "LossReason" RENAME TO "LossReason_old";

-- Create new enums
CREATE TYPE "EnquiryStatus" AS ENUM ('NEW', 'FOLLOW_UP', 'APPOINTMENT_FIXED', 'TEST_DRIVE', 'BOOKED', 'RETAIL_DONE', 'BOOKING_CANCEL', 'RETAIL_CANCEL', 'ENQUIRY_CLOSED');
CREATE TYPE "LossReason" AS ENUM ('OTHER_REASON', 'CO_DEALER', 'OUT_OF_TERRITORY');

-- enquiries.status (has a default, must drop/reset it around the type change)
ALTER TABLE "enquiries" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "enquiries" ALTER COLUMN "status" TYPE "EnquiryStatus" USING (
  CASE "status"::text
    WHEN 'NEW' THEN 'NEW'
    WHEN 'CONTACTED' THEN 'FOLLOW_UP'
    WHEN 'FOLLOW_UP' THEN 'FOLLOW_UP'
    WHEN 'APPOINTMENT_SCHEDULED' THEN 'APPOINTMENT_FIXED'
    WHEN 'APPOINTMENT_NO_SHOW' THEN 'FOLLOW_UP'
    WHEN 'TEST_DRIVE_DONE' THEN 'TEST_DRIVE'
    WHEN 'FEEDBACK_COLLECTED' THEN 'TEST_DRIVE'
    WHEN 'QUOTATION_SHARED' THEN 'TEST_DRIVE'
    WHEN 'NEGOTIATION' THEN 'TEST_DRIVE'
    WHEN 'BOOKING_CONFIRMED' THEN 'BOOKED'
    WHEN 'FINANCE_IN_PROGRESS' THEN 'BOOKED'
    WHEN 'EXCHANGE_IN_PROGRESS' THEN 'BOOKED'
    WHEN 'SALE_CLOSED' THEN 'RETAIL_DONE'
    WHEN 'DELIVERY_IN_PROGRESS' THEN 'RETAIL_DONE'
    WHEN 'DELIVERED' THEN 'RETAIL_DONE'
    WHEN 'LOST' THEN 'ENQUIRY_CLOSED'
  END
)::"EnquiryStatus";
ALTER TABLE "enquiries" ALTER COLUMN "status" SET DEFAULT 'NEW';

-- enquiries.lossReason (nullable, no default)
ALTER TABLE "enquiries" ALTER COLUMN "lossReason" TYPE "LossReason" USING (
  CASE "lossReason"::text
    WHEN 'PRICE_TOO_HIGH' THEN 'OTHER_REASON'
    WHEN 'BOUGHT_COMPETITOR' THEN 'OTHER_REASON'
    WHEN 'BOUGHT_ANOTHER_BRANCH' THEN 'CO_DEALER'
    WHEN 'NOT_INTERESTED_ANYMORE' THEN 'OTHER_REASON'
    WHEN 'FINANCE_REJECTED' THEN 'OTHER_REASON'
    WHEN 'NO_RESPONSE' THEN 'OUT_OF_TERRITORY'
    WHEN 'OTHER' THEN 'OTHER_REASON'
    ELSE NULL
  END
)::"LossReason";

-- enquiry_status_history.fromStatus (nullable) and toStatus (not null) — same status mapping
ALTER TABLE "enquiry_status_history" ALTER COLUMN "fromStatus" TYPE "EnquiryStatus" USING (
  CASE "fromStatus"::text
    WHEN 'NEW' THEN 'NEW'
    WHEN 'CONTACTED' THEN 'FOLLOW_UP'
    WHEN 'FOLLOW_UP' THEN 'FOLLOW_UP'
    WHEN 'APPOINTMENT_SCHEDULED' THEN 'APPOINTMENT_FIXED'
    WHEN 'APPOINTMENT_NO_SHOW' THEN 'FOLLOW_UP'
    WHEN 'TEST_DRIVE_DONE' THEN 'TEST_DRIVE'
    WHEN 'FEEDBACK_COLLECTED' THEN 'TEST_DRIVE'
    WHEN 'QUOTATION_SHARED' THEN 'TEST_DRIVE'
    WHEN 'NEGOTIATION' THEN 'TEST_DRIVE'
    WHEN 'BOOKING_CONFIRMED' THEN 'BOOKED'
    WHEN 'FINANCE_IN_PROGRESS' THEN 'BOOKED'
    WHEN 'EXCHANGE_IN_PROGRESS' THEN 'BOOKED'
    WHEN 'SALE_CLOSED' THEN 'RETAIL_DONE'
    WHEN 'DELIVERY_IN_PROGRESS' THEN 'RETAIL_DONE'
    WHEN 'DELIVERED' THEN 'RETAIL_DONE'
    WHEN 'LOST' THEN 'ENQUIRY_CLOSED'
    ELSE NULL
  END
)::"EnquiryStatus";

ALTER TABLE "enquiry_status_history" ALTER COLUMN "toStatus" TYPE "EnquiryStatus" USING (
  CASE "toStatus"::text
    WHEN 'NEW' THEN 'NEW'
    WHEN 'CONTACTED' THEN 'FOLLOW_UP'
    WHEN 'FOLLOW_UP' THEN 'FOLLOW_UP'
    WHEN 'APPOINTMENT_SCHEDULED' THEN 'APPOINTMENT_FIXED'
    WHEN 'APPOINTMENT_NO_SHOW' THEN 'FOLLOW_UP'
    WHEN 'TEST_DRIVE_DONE' THEN 'TEST_DRIVE'
    WHEN 'FEEDBACK_COLLECTED' THEN 'TEST_DRIVE'
    WHEN 'QUOTATION_SHARED' THEN 'TEST_DRIVE'
    WHEN 'NEGOTIATION' THEN 'TEST_DRIVE'
    WHEN 'BOOKING_CONFIRMED' THEN 'BOOKED'
    WHEN 'FINANCE_IN_PROGRESS' THEN 'BOOKED'
    WHEN 'EXCHANGE_IN_PROGRESS' THEN 'BOOKED'
    WHEN 'SALE_CLOSED' THEN 'RETAIL_DONE'
    WHEN 'DELIVERY_IN_PROGRESS' THEN 'RETAIL_DONE'
    WHEN 'DELIVERED' THEN 'RETAIL_DONE'
    WHEN 'LOST' THEN 'ENQUIRY_CLOSED'
  END
)::"EnquiryStatus";

-- Drop old enums
DROP TYPE "EnquiryStatus_old";
DROP TYPE "LossReason_old";
